ru translate pages:
single-spa/ru.single-spa.js.org pull request #1
Opened 2020-12-01 21:43 UTC by Smekalin

- getting started
- examples
- videos
- single-spa playground
- part of sidebar

2020-12-01 21:45 UTC, Smekalin commented
@joeldenning I can't select @astra1 as a reviewer :\

2020-12-01 22:20 UTC, joeldenning commented
@astra1 hasn't accepted their invitation to this repository yet, which is why you can't assign them as a reviewer.

2020-12-01 22:30 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +## Примеры от основной команды
@Smekalin maybe replace `основной` with `ядра`?

2020-12-01 22:49 UTC, astra1 requested changes
@Smekalin @joeldenning review is done for now, thank you in advance!

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +- [coexisting-angular-microfrontends](https://github.com/joeldenning/coexisting-angular-microfrontends) это полноценный репозиторий микрофронтенда с Angular 9 который совмещает три отдельных Angular
@Smekalin please, consider to replace `отдельных` with `различных`

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +- [single-spa-portal-example](https://gitlab.com/TheMcMurder/single-spa-portal-example) это отличный пример сосуществования трех микрофронтендов на React.
@Smekalin consider to replace end with `трех React микрофронтендов`

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +- [single-spa-parcel-example](https://github.com/Guillembonet/single-spa-parcel-example) является примером микрофронтендов на Vue и React, содержащие Vue и React parcels соответственно и два Node.js
@Smekalin we must rearrange the sentence and use some common naming for `parcel` like `участок`, `зона` or better variant. Please, look at [multitran](https://www.multitran.com/m.exe?l1=1&l2=2&s=parcel)

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +- [single-spa-login-example-with-npm-packages](https://github.com/jualoppaz/single-spa-login-example-with-npm-packages) это пример single-spa приложения, которое импортирует зарегистрированные прилож
@Smekalin consider to replace `зарегистрированные ` with `указанные`

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +- [single-spa-html with js example](https://github.com/filoxo/single-spa-html-with-js-example) это пример репозитория использует single-spa-html, который дополнен простым JavaScript.
@Smekalin consider to replace `простым` with `чистым`

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +- [coexisting-angular-microfrontends/login](https://github.com/Vallerious/coexisting-angular-microfrontends/tree/feature/login) эта ветка реализует функционал авторизации между приложениями на Angula
@Smekalin you've used `аутентификации` before, `авторизация` is different process. And replace a second sentence with `LocalStorage API используется как общее пространство памяти для получения и сохранения токена.`

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +- [single-spa application with Webpack lazyStyleTag](https://github.com/filoxo/single-spa-example-webpack-lazystyletag) это простой пример, который использует функциональность lazyStyleTag Webpack st
@Smekalin please, consider to replace `...lazyStyleTag Webpack style-loader` with `...загрузчика стилей вебпака lazyStyleTag...`

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +- [single-spa shared state utility using Rxjs](https://github.com/filoxo/single-spa-example-rxjs-shared-state) показывает, как использовать служебный модуль, который совместно использует состояние пр
@Smekalin `использовать как модуль, который совместно использует` looks unnatural for my ears :)

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/examples.md
> +У вас есть свой пример или стартер-репозиторий? [Отправить PR](https://github.com/single-spa/single-spa.js.org/edit/master/website/versioned_docs/version-5.x/examples.md), чтобы добавить ваш пример в
@Smekalin consider to replace `стартер-репозиторий` with `репозиторий для старта`

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/single-spa-playground.md
> +Single-spa playground это интерактивное руководство, которое позволяет вам тестировать ваш код браузере в реальном времени, чтобы проверить, как он может работать с single-spa.
@Smekalin consider to replace `чтобы проверить, как он может работать с single-spa` with `чтобы проверить интеграцию с single-spa`

2020-12-01 22:49 UTC, astra1 commented on website/versioned_docs/version-5.x/videos.md
> +## От основной команды
@Smekalin same `ядра` usage

2020-12-07 07:52 UTC, Smekalin commented
@astra1 Thanks for the quick respond! I've done.

2020-12-07 16:55 UTC, astra1 approved these changes
Legitimate 💓

2020-12-07 18:58 UTC, joeldenning commented
Feel free to merge these pull requests yourselves - you don't need to wait for me to merge it.

2020-12-08 10:39 UTC, merged